// Generated by CoffeeScript 1.4.0
var assets, express, http, topology;

http = require('http');

assets = require('connect-assets');

express = require('express');

topology = require('./topology');

module.exports = {
  start: function(root) {
    var app;
    app = express();
    app.set('views', root + '/views');
    app.set('view engine', 'jade');
    app.use(express.logger('dev'));
    app.use(assets());
    app.use(express["static"](root + '/public'));
    app.get('/', function(req, res) {
      return res.render('index');
    });
    app.get('/main_controller.html', function(req, res) {
      return res.render('main_controller');
    });
    app.get('/topology/:tile', function(req, res) {
      return topology.getTile(root + '/tiles', req.params.tile, function(error, tile) {
        if (!error) {
          return res.send(tile);
        }
        return res.send([]);
      });
    });
    return http.createServer(app).listen(3000, function() {
      return console.log('http://localhost:3000');
    });
  }
};
