// Generated by CoffeeScript 1.4.0
var fs, tiles, topology;

fs = require('fs');

tiles = {};

topology = {
  getTile: function(path, id, callback) {
    if (tiles[id]) {
      callback(null, tiles[id]);
      return;
    }
    return topology.readTile(path, id, callback);
  },
  readTile: function(path, id, callback) {
    var file;
    file = path + '/' + id + '.hgt';
    return fs.readFile(file, function(err, buf) {
      var col, count, elevation, elevations, offset, readings, row, side, start, step, _i, _j, _ref;
      step = 2;
      readings = buf.length / step;
      count = Math.sqrt(readings);
      elevations = [];
      offset = 0;
      side = 255;
      start = 1201 - side - 1;
      for (row = _i = start; start <= 1200 ? _i <= 1200 : _i >= 1200; row = start <= 1200 ? ++_i : --_i) {
        for (col = _j = 400, _ref = 400 + side; 400 <= _ref ? _j <= _ref : _j >= _ref; col = 400 <= _ref ? ++_j : --_j) {
          offset = row * count + col;
          elevation = buf.readInt16BE(offset * 2);
          elevations.push(elevation);
        }
      }
      console.log('count;', Math.sqrt(elevations.length));
      tiles[id] = {
        length: 12000,
        count: Math.sqrt(elevations.length),
        elevations: elevations
      };
      return callback(null, tiles[id]);
    });
  }
};

module.exports = topology;
