// Generated by CoffeeScript 1.4.0
var fs, tiles, topology;

fs = require('fs');

tiles = {};

topology = {
  getTile: function(path, id, callback) {
    if (tiles[id]) {
      callback(null, tiles[id]);
    }
    return topology.readTile(path, id, callback);
  },
  readTile: function(path, id, callback) {
    var file;
    file = path + '/' + id + '.hgt';
    return fs.readFile(file, function(err, buf) {
      var count, elevation, elevations, offset, readings, step;
      step = 2;
      readings = buf.length / step;
      count = Math.sqrt(readings);
      elevations = [];
      offset = 0;
      try {
        while (true) {
          elevation = buf.readInt16BE(offset);
          elevations.push(elevation);
          offset += step;
        }
      } catch (error) {
        if (error.message !== 'Trying to read beyond buffer length') {
          callback(error, []);
        }
      }
      return callback(null, {
        length: 5000,
        count: count,
        elevations: elevations
      });
    });
  }
};

module.exports = topology;
