// Generated by CoffeeScript 1.4.0

module.exports = {
  getTile: function(id) {
    return {
      length: 500,
      count: 4,
      elevations: [100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -100]
    };
  }
};
